apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: APIs
  annotations:
    github.com/project-slug: phillim1/APIs
  links:
    - url: https://confluence.finastra.com/display/ARPP/FusionOperate+Catalog+Portal+Requirements
spec:
  type: other
  lifecycle: unknown
  owner: backstage
