apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: APIs
  annotations:
    github.com/project-slug: phillim1/APIs
  links:
    - url: https://dashboard.example.com
      title: Marts Dashboard
      icon: dashboard
spec:
  type: other
  lifecycle: unknown
  owner: backstage
