apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Marts APIs
  description: marts
  annotations:
    github.com/project-slug: phillim1/APIs
spec:
  type: openapi
  lifecycle: development
  owner: backstage
  system: marts-apis
  definition: https://github.com/phillim1/APIs/blob/master/Swagger.json
